### PR TITLE
tools: update trace-cmd to 2.8.3

### PR DESCRIPTION
**Pull request by vdonnefort**
The main motivation behind this update is to fix a segfault which has been
encountered on AOSP.

### CODE REVIEW

**Comment by douglas-raillard-arm** [comment]
I'm giving it a test round. Are the binaries stripped ? It seems that their size is much larger (especially the arm one).

**Comment by vdonnefort** [comment]
Updated the branch with stripped binaries for all arch.

**Comment by valschneider** [comment]
I'm getting the following exception when trying to collect some events:
```
TargetStableError: Got exit code 2
from: export PATH=/root/devlib-target/bin:$PATH && export LC_ALL=C && /root/devlib-target/bin/trace-cmd reset
OUTPUT: trace-cmd: No such file or directory
  opening to '/sys/kernel/debug/tracing/tracing_max_latency'
```

Seems like it's related to `trace-cmd` itself:

```bash
$ trace-cmd
trace-cmd version 2.6.

$ trace-cmd reset

$ /root/devlib-target/bin/trace-cmd
trace-cmd version 2.8.3

$ /root/devlib-target/bin/trace-cmd reset
trace-cmd: No such file or directory
  opening to '/sys/kernel/debug/tracing/tracing_max_latency'
```

I'm trying to figure out what's going on.

**Comment by valschneider** [comment]
Seems like trace-cmd unconditionally writes to that file on reset, but it's not guaranteed to be there (you need the IRQ/preemption latency tracers on). We do have the IRQ latency tracer on for our integration branch, so it's not that bad... I'll send out an email to the trace-cmd folks.

**Comment by valschneider** [comment]
Filed at https://bugzilla.kernel.org/show_bug.cgi?id=205241

**Comment by douglas-raillard-arm** [comment]
@JaviMerino Does the production devices' kernel you experiment with have that '/sys/kernel/debug/tracing/tracing_max_latency' file ?

**Comment by JaviMerino** [comment]
> @JaviMerino Does the production devices' kernel you experiment with have that '/sys/kernel/debug/tracing/tracing_max_latency' file ?

No, none of the three I have tested have that file.

**Comment by douglas-raillard-arm** [comment]
Superseded by https://github.com/ARM-software/lisa/pull/1156

Closing as trace-cmd v2.8.3 cannot be used due to trace-cmd unconditionally opening `/sys/kernel/debug/tracing/tracing_max_latency`.

**Pull request closed without merging**
