### PR TITLE
submodules: update trappy to v5.7.0,  bart to v1.6.0 and devlib to b9a1698

### PR DESCRIPTION
**Pull request by JaviMerino**
- Ability to choose colours in LinePlot, ILinePlot and EventPlot
- Performance improvements for ILinePlot
- Bug fix for wake migration test

only to name a few.  This month's trappy and bart update is full of awesomeness!

### CODE REVIEW

**Comment by mdigiorgio** [comment]
Could you please add `devlib` as well?

**Comment by JaviMerino** [comment]
Sure, I'll wait for ARM-software/devlib#54 to be merged and update devlib to that

**Comment by mdigiorgio** [comment]
:+1:  great

**Comment by JaviMerino** [comment]
Updated to include devlib

**Comment by mdigiorgio** [comment]
Thanks, let's merge it :smile:

**Pull request merged**
