### PR TITLE
Geekbench corporate

### PR DESCRIPTION
**Pull request by valschneider**
I'm not too keen on the naming for the TAB & ENTER input methods. I think press_tab() and press_enter() would've been better, but I also wanted to keep them aligned with the other methods - home(), back()... Feedback on that would be nice.

### CODE REVIEW

**Comment by valschneider** [comment]
Set airplane mode during the benchmark

**Comment by derkling** [comment]
Is that really working on more than one single device?
Otherwise, we should report it as "not yet ready to merge"

**Comment by valschneider** [comment]
Well, it does work on both HiKey & Pixel.

**Comment by bjackman** [comment]
This is now supported by wltests

**Pull request closed without merging**
