### PR TITLE
Add support for custom trace analysis using callbacks

### PR DESCRIPTION
**Pull request by cobrien7**
Some trace analysis tasks are most easily expressed by iterating over
events in chronological order. Add a runCustomAnalysis() method to the
Trace class that will run user-defined functions on trace events in
the order they occurred.

Signed-off-by: Connor O'Brien <connoro@google.com>

### CODE REVIEW

**Comment by cobrien7** [comment]
This change depends on Joel's trappy PR adding a __line column to the trace dataframes (https://github.com/ARM-software/trappy/pull/251)

**Comment by bjackman** [comment]
If this is fast enough then I think it seems like a sensible approach. One request... could you add some basic test coverage? [Here's] a pending commit that adds a unit test for part of the `Trace` class, maybe you could use something like that? (Don't worry about merge conflicts)

Would be great just to have enough coverage that the CI fails on this PR until the "__line" PR is merged in TRAPpy.

**Comment by derkling** [comment]
Cool, @sinkap merged this:
    https://github.com/ARM-software/trappy/pull/251

Thus we can now refresh this PR by adding a commit to progress libs/trappy

You just need to add a patch which "git add libs/trappy" once you pulled master in your local lib/trappy folder. This is an example commit message: https://github.com/ARM-software/lisa/commit/70aa3a3eaf9c3d894642d61c074ad718e7620ed3
Just add a similar patch at the beginning of this PR.

**Comment by cobrien7** [comment]
Just talked to Joel about whether it might make more sense to put this in trappy instead, e.g. as a method for the GenericFTrace class. I'm going to go ahead and do that (and write an accompanying test in trappy/tests) unless there are any objections or problems with that approach

**Comment by joelagnel** [comment]
Is being moved to https://github.com/ARM-software/trappy/issues/254 . Please close.

**Comment by derkling** [comment]
This code is going to be merged in TRAPpy (ARM-software/trappy#254) while in LISA we will expect a new PR to add example analysis using this new API. So, let's close this one.

**Pull request closed without merging**
