### PR TITLE
Add more PELT tests

### PR DESCRIPTION
**Pull request by mdigiorgio**
This series adds:

- a couple of improvements to the `_LoadTrackingBase` base class
- a test for PELT tasks' utilization signals while using `schedutil` as governor
- a test for CFS runqueues' utilization

### CODE REVIEW

**Comment by valschneider** [comment]
I believe this is redundant with what @Elieva has been working on, am I correct ?

**Comment by derkling** [comment]
@Elieva, can you please have a look at the above patches to check if some of the proposed fixes/updates are still relevant after your #556 patches? Thanks.

**Comment by Elieva** [comment]
I think the third commit(tests: load_tracking: add CFS runqueues' utilization test ) is similar to #551 because they both test the same behavior (task that migrates between cpus).
But the two other commits seem unrelated to the patches #556 and #551

**Comment by valschneider** [comment]
I think this is mostly superseded by the abstraction done in `analysis/load_tracking.py`. Can this be closed?

**Comment by douglas-raillard-arm** [comment]
Closing as the base code has changed too much and the PR would need reimplementation

**Pull request closed without merging**
