### PR TITLE
Update subtrees

### PR DESCRIPTION
**Pull request by douglas-raillard-arm**

### CODE REVIEW

**Comment by douglas-raillard-arm** [comment]
> Do you know why github's complaining about merge conflicts?

It complains if two PRs are conflicting, which is the case since they would touch the same places in the same files. Maybe yours has one less or one more change factored in, so they are not exactly the same.

**Comment by douglas-raillard-arm** [comment]
Stalled until https://github.com/ARM-software/devlib/issues/428 gets fixed

**Comment by douglas-raillard-arm** [comment]
https://github.com/ARM-software/devlib/issues/428 now fixed and PR updated

**Comment by valschneider** [comment]
Github's still reporting conflicts, did we mess up our subtrees in some way? :/

**Pull request merged**
