### PR TITLE
utils/wa_results_collector: Change sha1 acquisition method

### PR DESCRIPTION
**Pull request by valschneider**
To map a WA run with a kernel commit sha1, we currently read whatever
__meta/target_info.json reports for "kernel_release" (which should be
the equivalent of uname -r).

However, there are cases where this doesn't seem to be reported. For
instance, a HiKey960 built with hikey960_defconfig will not report the
commit sha1 in its version data, which will cause an exception in the
results collector code.

Since the sha1 is included in the results directory name anyway, use
that instead as a more reliable source.

### CODE REVIEW

**Comment by derkling** [comment]
LGTM, however I was wondering if it could make sense to check before the WA output... and fallback to the dir parsing only in case the first one should fails.

**Comment by valschneider** [comment]
@derkling Makes sense to me. I was hoping to find a "centralized" source of information for that sha1, but as you point out the data could be generated without using **test_series**. I'll fold the old method back in.

**Comment by vingu-linaro** [comment]
Hi, I confirm that we are not encoding the sha1 in the WA output folder name when using wa_results_collector in our ci loop

**Comment by valschneider** [comment]
@vingu-linaro Thanks for the confirmation, I'll only add reading the dir name as a fallback.

**Pull request merged**
